### PR TITLE
BT-324 Added Routers to CloudComputeCow

### PR DESCRIPTION
**Pull request by kshakir**

### CODE REVIEW

**Review by yonghaoy — APPROVED** [review]
Chang looks good. But to use that, we will need to publish a new version of compute package.
Update package version here:
https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/master/google-compute/gradle.properties
Then manually publish it(sorry, auto publish is broken by a recent Vault change, we haven't gotten chance to fix it yet).

@wchamber recently did a manually publish, he might know the command to run.

**Comment by wchamber** [comment]
> Chang looks good. But to use that, we will need to publish a new version of compute package.
> Update package version here:
> https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/master/google-compute/gradle.properties
> Then manually publish it(sorry, auto publish is broken by a recent Vault change, we haven't gotten chance to fix it yet).
> 
> @wchamber recently did a manually publish, he might know the command to run.

re: manual publish, see also https://broadworkbench.atlassian.net/browse/PF-722
1. Merge your change to master
2. Pull master
3. Modify the [list of publications](https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/da65c0500048582bfbb7a1136a69befdb6d0272d/build.gradle#L28-L41) to only be the new packages, e.g. `google-compute`
4. Set the ARTIFACTORY_* environment variables like [how the publish workflow does](https://github.com/DataBiosphere/terra-cloud-resource-lib/blob/da65c0500048582bfbb7a1136a69befdb6d0272d/.github/workflows/publish.yml#L60-L64) (pull the secrets from vault path `secret/dsp/accts/artifactory/dsdejenkins`)
5. Run `.gradlew artifactoryPublish`
5. Verify the new version exists at https://broadinstitute.jfrog.io/ui/native/libs-release/bio/terra/cloud-resource-lib/google-compute

**Review by mcovarr — APPROVED** [review]

**Comment by kshakir** [comment]
`google-compute` version bumped to `0.12.0`. Will merge in a couple of hours unless someone objects.

**Comment by kshakir** [comment]
@yonghaoy / @wchamber Soo... I just noticed that someone else needs to merge CRL PRs.

Screen Shot 2021-07-23 at 1 13 28 PM

Do either of you have permission to merge or should we summon someone else?

I can run the manual publish after the merge unless someone else does it first.

**Comment by wchamber** [comment]
Interesting, don't think that was particularly intentional. I went ahead and merged it.

**Comment by kshakir** [comment]
Thanks for the merge. Published from `master`: https://broadinstitute.jfrog.io/broadinstitute/libs-release-local/bio/terra/cloud-resource-lib/google-compute/0.12.0/

**Pull request merged**
