### PR TITLE
add CloudBillingClient#testIamPermissions

### PR DESCRIPTION
**Pull request by rtitle**
Needed for Billing Profile Manager.

### CODE REVIEW

**Comment by cahrens** [comment]
@rtitle I ran across a TODO in BPM about this PR. Why was it never merged? https://github.com/DataBiosphere/terra-billing-profile-manager/blob/ef8f6359ce3d1ef68cef575ea0b07d8c378dbe0f/service/build.gradle#L41

**Comment by rtitle** [comment]
Um, it's hazy but I think I was experiencing connected test failures in CRL around project allocation. (Of course, the test logs are gone now.) Also I can't spot any particular issues at the moment, but I have a recollection that GCP support in BPM needed a bit more testing and verification of correctness -- I may have been holding off merging this until we confirmed it with BPM.

**Comment by cahrens** [comment]
Some of these files don't even exist anymore. I'm concerned that BPM appears stuck on this very old version.

**Comment by rtitle** [comment]
CRL at some point after this PR underwent a large refactor to un-modularize things -- there used to be a gradle module for each cloud library (google-billing, azure-compute, etc). Now it's just 1 dependency (with packages per cloud library).

**Comment by cahrens** [comment]
So… does that mean that BPM should change how its dependency is declared? But presumably there was something important in this PR that was needed for BPM, so I suspect this would cause something to break? https://github.com/DataBiosphere/terra-billing-profile-manager/blob/ef8f6359ce3d1ef68cef575ea0b07d8c378dbe0f/service/build.gradle#L41

**Comment by rtitle** [comment]
Re how the dependency is declared -- yes I think so.

I think BPM uses the method added in this PR [here](https://github.com/DataBiosphere/terra-billing-profile-manager/blob/main/service/src/main/java/bio/terra/profile/service/profile/flight/create/CreateProfileVerifyAccountStep.java#L35)

Sorry for leaving this not finished.. probably the right next steps are to get BPM on the latest CRL, and either re-do this functionality, or temporarily remove it from `CreateProfileVerifyAccountStep` (since BPM is not yet being used with GCP anyway).

**Comment by cahrens** [comment]
OK, I created https://broadworkbench.atlassian.net/browse/WOR-714

**Pull request closed without merging**
