### PR TITLE
Document that publish workflow is expected to fail

### PR DESCRIPTION
**Pull request by melissachang**

### CODE REVIEW

**Review by jmczerk — APPROVED** [review]

**Review by yonghaoy — APPROVED** [review]
It's still unclear on how to publish a package and it is a known issue,
You can link https://docs.google.com/document/d/1gSEmZX25PxR46kMQgOZKuyuThEOzXfg-aRlKLQT3sMc/edit#heading=h.47z3zhyf3s0z
OR https://broadworkbench.atlassian.net/browse/PF-722
here. That might be helpful

**Comment by melissachang** [comment]
> It's still unclear on how to publish a package and it is a known issue, You can link https://docs.google.com/document/d/1gSEmZX25PxR46kMQgOZKuyuThEOzXfg-aRlKLQT3sMc/edit#heading=h.47z3zhyf3s0z OR https://broadworkbench.atlassian.net/browse/PF-722 here. That might be helpful

I agree. I asked about this during standup, and John prefers not to link to private things from the README. Hopefully this PR will make it easier for the next person to find those links. :)

**Comment by melissachang** [comment]
> > It's still unclear on how to publish a package and it is a known issue, You can link https://docs.google.com/document/d/1gSEmZX25PxR46kMQgOZKuyuThEOzXfg-aRlKLQT3sMc/edit#heading=h.47z3zhyf3s0z OR https://broadworkbench.atlassian.net/browse/PF-722 here. That might be helpful
> 
> I agree. I asked about this during standup, and John prefers not to link to private things from the README.

(Since this is a public repo)

**Comment by jmczerk** [comment]
> > > It's still unclear on how to publish a package and it is a known issue, You can link https://docs.google.com/document/d/1gSEmZX25PxR46kMQgOZKuyuThEOzXfg-aRlKLQT3sMc/edit#heading=h.47z3zhyf3s0z OR https://broadworkbench.atlassian.net/browse/PF-722 here. That might be helpful
> > 
> > 
> > I agree. I asked about this during standup, and John prefers not to link to private things from the README.
> 
> (Since this is a public repo)

I'd been pointed away from referencing non-public Google docs or Jira tickets in the past, but I'd gladly defer to @yonghaoy's experience on this.

**Comment by yonghaoy** [comment]
> > It's still unclear on how to publish a package and it is a known issue, You can link https://docs.google.com/document/d/1gSEmZX25PxR46kMQgOZKuyuThEOzXfg-aRlKLQT3sMc/edit#heading=h.47z3zhyf3s0z OR https://broadworkbench.atlassian.net/browse/PF-722 here. That might be helpful
> 
> I agree. I asked about this during standup, and John prefers not to link to private things from the README. Hopefully this PR will make it easier for the next person to find those links. :)

Ah, that make sense! (hopefully we can fix this issue soon, then we longer need this workaround)

**Pull request merged**
